### ISSUE TITLE
Input text message difficult to identify

### ISSUE THREAD

**Issue by MacInsiderOrg** [usercare/ios-sdk#1]
Input text message difficult to identify because its color is almost equivalent to its background.
I noticed this error in iOS 9.3.2 on iPod Touch
Please tell me, how to fix this issue.

P.S. Maybe I just haven't found such a method that would help me change the color of the incoming message.
Thank you.

![14875376_917829511694417_2123902475_n](https://cloud.githubusercontent.com/assets/14976675/19759332/37356dda-9c35-11e6-89a4-d9e7ab043749.jpg)

**Comment by h32** [comment]
Hello Andrew,

Thanks for reporting that issue. Looks like issue of default color scheme. You can easily customize it via web [config](https://my.agent.ai) (Agent Desktop -> Configuration -> Your App -> UI Settings -> Messaging Settings) or via [code](https://github.com/usercare/ios-sdk/blob/master/Docs/advanced.md) if you would like to have different config for iOS and Android apps, check for **Agent Message Font Color** property. 

Let me know if you still have any issues.

Best regards,
Kirill

**Comment by MacInsiderOrg** [comment]
Thank you so much.
